apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
spec:
  selector:
    matchLabels:
      app: client-service
  replicas: 2
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
        - name: react-app
          image: gcr.io/golden-sandbox-343808/github.com/yadhursheeka/ctse-a2-react
          ports:
            - containerPort: 3000
